### ISSUE TITLE
Milestone "Type" is not working

### ISSUE THREAD

**Issue by spinytel** [spinytel/DjangoEmt#2]
Goto any project details. 
- Select Milestone -> Create Milestone 

![milestone](https://cloud.githubusercontent.com/assets/11073730/10120932/569b28b2-64f6-11e5-8c4b-3e0fc2b354bd.jpg)
- It will ask to select Milestone "Type". But there is an empty dropdown list without any default one. So you cannot select Milestone "Type" . And this will prevent you to create a Milestone. 
- Without Milestone you cannot create any ticket.

**Comment by mamun0024** [comment]
Milestone type - dropdown list value comes from database. I think there has no value. Thats why it's shows empty.

**Comment by aftnix** [comment]
Added to the DB table. closed
